# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dgamma <- function(x, k, theta) {
    .Call(`_bsvarSIGNs_log_dgamma`, x, k, theta)
}

log_dinvgamma <- function(x, alpha, beta) {
    .Call(`_bsvarSIGNs_log_dinvgamma`, x, alpha, beta)
}

log_prior_hyper <- function(hyper, model, prior) {
    .Call(`_bsvarSIGNs_log_prior_hyper`, hyper, model, prior)
}

log_mvgamma <- function(n, x) {
    .Call(`_bsvarSIGNs_log_mvgamma`, n, x)
}

log_ml <- function(b, Omega, Psi, d, Y, X) {
    .Call(`_bsvarSIGNs_log_ml`, b, Omega, Psi, d, Y, X)
}

log_ml_dummy <- function(hyper, model, Y, X, prior) {
    .Call(`_bsvarSIGNs_log_ml_dummy`, hyper, model, Y, X, prior)
}

log_posterior_hyper <- function(hyper, model, Y, X, prior) {
    .Call(`_bsvarSIGNs_log_posterior_hyper`, hyper, model, Y, X, prior)
}

extend_hyper <- function(init, model, hypers) {
    .Call(`_bsvarSIGNs_extend_hyper`, init, model, hypers)
}

narrow_hyper <- function(model, hypers) {
    .Call(`_bsvarSIGNs_narrow_hyper`, model, hypers)
}

sample_hyper <- function(S, start, init, model, Y, X, W, prior) {
    .Call(`_bsvarSIGNs_sample_hyper`, S, start, init, model, Y, X, W, prior)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bsvarSIGNs_RcppExport_registerCCallable`)
})
